SELECT count( distinct o.CUSTOMER_ID) as customers_per_order, o.TRANSACTION_ID, o.TRANSACTION_DATE,
sum(o.QUANTITY) AS total_quantity, 
sum(o.DELIVERY_CHARGES) AS total_delivery_charges,
sum(o.REVENUE) AS total_revenue,
o.TRANSACTION_YEAR,o.TRANSACTION_MONTH,o.TRANSACTION_MONTH_STR,o.TRANSACTION_DAY_OF_MONTH, o.TRANSACTION_DAY_OF_WEEK 
FROM {{ref('prep_online_sales')}} o
GROUP BY o.TRANSACTION_ID, o.TRANSACTION_DATE,o.TRANSACTION_YEAR,o.TRANSACTION_MONTH,o.TRANSACTION_MONTH_STR,o.TRANSACTION_DAY_OF_MONTH, o.TRANSACTION_DAY_OF_WEEK