version: 2
sources:

- name: data
  schema: team_3
  tables:
    - name: customers
    - name: discount_coupon
    - name: marketing_spend
    - name: online_sales 
    - name: tax_amount 
    - name: monthly_kpi_summary


- name: external
  schema: team_3
  tables:
    - name: holidays_2019_us
